### ISSUE TITLE
Patch size change for image restoration

### ISSUE THREAD

**Issue by anitchris** [cszn/KAIR#100]
It would be really helpful if you could tell whether we could change the patch size from 128 to 64 for denoising task? There has been an ablation study about it. Would it create much difference in the the performance?

**Comment by JingyunLiang** [comment]
The ablation study is for classical SR (2X). I haven't done ablation study on patch size yet for denoising, but a common practice is that using larger patch size is better. Most state-of-the-art denoising methods use 256x256 patch sizes. In our experiments, we use 128x128 due to GPU limit (11G 2080ti). If you can train it with larger patch sizes, I think there will be a performance improvement.
