### ISSUE TITLE
SwinIR JPEG CAR in color?

### ISSUE THREAD

**Issue by jxtps** [cszn/KAIR#105]
The pretrained grayscale model works quite well for compression artefact reduction! Did you get a chance to try training a color model as well? Did that not work for some reason? 

Are there any known issues / gotchas with changing `train_swinir_car_jpeg.json` to have `"is_color": true` - it looks like `dataset_jpeg.py` was written to handle that case? Need to also change the `in_chans` to 3 of course, but maybe also need to increase e.g. `embed_dim` to increase the "bandwidth" of the model to make room for the color information? 

I've noticed that a lot of JPEG CAR papers work in grayscale, but I'm not clear on why that is?

**Comment by jxtps** [comment]
Also, for how many iters/steps did you train the grayscale car jpeg? I'm trying to reproduce your training run. 

`Number of train images: 8,794, iters: 1,100` - does that match what you had? Thanks!

**Comment by JingyunLiang** [comment]
I think it should work well for color mode. We only report results on grayscale model because most papers in this field use the grayscale setting. There is no need to modify the network details except the input and output layers (from channel 1 to 3).

The details on training is given in the supplementary and can also be found in this repo.
