### ISSUE TITLE
The choice of LRscheduler: MultistepLR or ConsineAnnealing

### ISSUE THREAD

**Issue by mrluin** [cszn/KAIR#137]
Hello,

I notice that the training of SwinIR adopts MultistepLR scheduler but the training of VRT uses CosineAnnealing (which is commonly used in recent works). And I have also tested using CosineAnnealing+adam optimizer setting (which is the same with VRT) to train SwinIR model, however compared with simple MultistepLR, i cannot get better results (in whichPSNR grows first but collapse in later iterations).

Could you give me some hints or advices about the choice of optimizer setting? Thanks in advance!

**Comment by JingyunLiang** [comment]
I think using CosineAnnealing or MultistepLR achieves similar performance in our experiments (I haven't met model collapse before). We just follow the common settings of image/ video SR methods. By the way, I think MultistepLR is more flexible because you can adjust different milestones flexibly. In contrast, CosineAnnealing may have some "wasted iterations" that the model does not improve much due to the cosine annealing scheme.
